<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">


  <!-- ROCKER -->
  <xacro:macro name="rocker"  params="robot_name prefix joint_type location *joint_limits">

    <link name="${robot_name}_${prefix}_rocker_link">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}" />
        <geometry>
          <mesh filename="package://ridgeback_description/meshes/rocker.stl"/>
        </geometry>
        <material name="black" />
      </visual>
      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="10.267"/>
        <inertia
          ixx="0.0288" ixy="2.20484e-6" ixz="-1.3145e-5"
          iyy="0.4324" iyz="1.8944e-3"
          izz="0.4130"/>
      </inertial>
    </link>

    <joint name="${robot_name}_${prefix}_rocker" type="${joint_type}">
      <parent link="${robot_name}_axle_link"/>
      <child link="${robot_name}_${prefix}_rocker_link" />
      <origin xyz="${location*rocker_offset} 0 0" rpy="0 0 0" />
      <axis xyz="1 0 0" />
      <xacro:insert_block name="joint_limits" />
    </joint>

    <!-- WHEELS-->
    <xacro:wheel robot_name="${robot_name}" prefix="${prefix}" side="left">
      <origin xyz="0 ${rocker_width/2 + wheel_width/2} 0" rpy="0 0 0" />
    </xacro:wheel>

    <xacro:wheel robot_name="${robot_name}" prefix="${prefix}" side="right">
      <origin xyz="0 ${-(rocker_width/2 + wheel_width/2)} 0" rpy="0 0 0" />
    </xacro:wheel>

  </xacro:macro>

</robot>
